### ISSUE TITLE
How can I change the i2c address?

### ISSUE THREAD

**Issue by VanDraven** [othermod/I2C-Linux-Gamepad-using-ADS1015-ADS1115-and-MCP23017#1]
Hi,
I'm trying to use your code with a PCF8591 (for test) and later a ADS1015.
For now it is not working and I suspect that might be because the i2c address of the PCF8591 is 0x48.
Is there a way to change that?

**Comment by othermod** [comment]
Sorry for the very delayed response, but I didn't have notifications on. The PCF8591 and ADS1015 work differently in how they communicate. I'll make a page for the PCF8591 in the near future.

I just updated the code to make it easier to change the I2C address, so if that conflict was causing problems then it's easy to resolve now.
