### ISSUE TITLE
Waveshare MCP23017 IO Expansion Board

### ISSUE THREAD

**Issue by ghost** [othermod/I2C-Linux-Gamepad-using-ADS1015-ADS1115-and-MCP23017#5]
I couldn't find the one in your video in my region so I picked this up https://www.waveshare.com/mcp23017-io-expansion-board.htm. I wired it right and I get an error saying: MCP23017 was not detected at address 0x20. I switched sda and clk but same result, I also wired it to 5v but same error. Does the driver not work with this board?

**Comment by ghost** [comment]
Found out the default address of the module is 0x27. Can I modify from software or do I need to mod the board?

**Comment by othermod** [comment]
You can change the address in the code. Look for #define MCP_ADDR 0x20 in gamepad.c and change it to #define MCP_ADDR 0x27

**Comment by ghost** [comment]
> You can change the address in the code. Look for #define MCP_ADDR 0x20 in gamepad.c and change it to #define MCP_ADDR 0x27

it still dosen't work. If I do i2cdetect -y 1 they appear

**Comment by ghost** [comment]
nvm forgot to recompile.
