### ISSUE TITLE
Right Thumbstick Doesn't Get Detected On Startup

### ISSUE THREAD

**Issue by Haydn-HS** [othermod/I2C-Linux-Gamepad-using-ADS1015-ADS1115-and-MCP23017#6]
I am using a pi 4 b and the same MCP23017 & ADS1015 as you did in the guide and video, the issue isn't when I first run the command `sudo ./gamepad -j 2 &` as when I run it for the first time all buttons and both joysticks work, but once I run `setup.sh` and reboot only one joystick will work and when I do jstest there are only 2 axes unless I do `sudo ./gamepad -j 2 &`  I'm not sure what the issue is as I have done this about 6 times now with having it start on boot both with `setup.sh` and the code in the `readme` file which I believe is the manual process. I appreciate any help you can provide.

Haydn.

**Comment by othermod** [comment]
Hey @Haydn-HS I just saw this issue was closed. I assume you were able to resolve it? 
I believe it was defaulting to just the one joystick, I can add some extra options during setup to allow people to choose between 1 and 2.

**Comment by Haydn-HS** [comment]
@othermod Thanks for the response and sorry for posting my issue, I had set it up and when I didn’t work I’d have a js1 js2 and so on and only a little while after I posted it I noticed you did a kill all command. If possible I think that having an option for joysticks would be a great idea but on the most part I think it’s just that the default I think was one joystick as when I install it and straight off whe I do jstest there are only 2 axes so when there the setup or even on the first run of Gamepad.c with a joystick selection would come in handy, thanks again.
Haydn
